// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.MACAddressLookup
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("mac")]
        public string Mac { get; set; }

        [JsonProperty("isValid")]
        public bool? IsValid { get; set; }

        [JsonProperty("vendor")]
        public string Vendor { get; set; }

        [JsonProperty("oui")]
        public string Oui { get; set; }

        [JsonProperty("formats")]
        public Formats Formats { get; set; }
    }

    public partial class Formats
    {
        [JsonProperty("colon")]
        public string Colon { get; set; }

        [JsonProperty("dash")]
        public string Dash { get; set; }

        [JsonProperty("dot")]
        public string Dot { get; set; }

        [JsonProperty("raw")]
        public string Raw { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
