// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.MACAddressLookup
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("mac")]
        public string Mac { get; set; }

        [JsonProperty("vendor")]
        public string Vendor { get; set; }

        [JsonProperty("dotNotation")]
        public string DotNotation { get; set; }

        [JsonProperty("hexFormat")]
        public string HexFormat { get; set; }

        [JsonProperty("bitReversed")]
        public string BitReversed { get; set; }

        [JsonProperty("byteString")]
        public string ByteString { get; set; }

        [JsonProperty("base16")]
        public string Base16 { get; set; }
    }
}
